=== itanaskovic/accounting/accounting-reporting/src/reporting_config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 Copyright 2013 thorsten frank (thorsten.frank@gmx.de).
    
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!--  -->
    <xs:element name="AccountingReports" type="AccountingReports"/>

    <!--  -->
    <xs:complexType name="AccountingReports">
        <xs:sequence>
            <xs:element name="Reports" type="Reports" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>
    
    <!--  -->
    <xs:complexType name="Reports">
        <xs:sequence>
            <xs:element name="Report" type="Report" minOccurs="1" maxOccurs="unbounded">
                <xs:unique name="UniqueReportId">
                    <xs:selector xpath="Report" />
                    <xs:field xpath="@id" />
                </xs:unique>            
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <!--  -->
    <xs:complexType name="Report">
        <xs:sequence>
            <xs:element name="Model" type="Model" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="template" type="xs:string" use="required"/>
    </xs:complexType>
    
    <!--  -->
    <xs:complexType name="Model">        
        <xs:attribute name="id" type="xs:string" use="required"/>
        <xs:attribute name="class" type="xs:string" use="required"/>
    </xs:complexType>
</xs:schema>

=== itanaskovic/accounting/accounting-reporting/config/reporting_config.xml
<?xml version="1.0" encoding="UTF-8"?>
<AccountingReports xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reporting_config.xsd">
  <Reports>
    <Report id="Invoice" template="InvoiceTemplate.jasper" >
        <Model id="invoice" class="de.togginho.accounting.model.Invoice" />
    </Report>
    <Report id="Letterhead" template="Letterhead.jasper">
      <Model id="user" class="de.togginho.accounting.model.User" />
    </Report>
    <Report id="CashFlowStatement" template="CashFlowStatement.jasper">
      <Model id="cashFlow" class="de.togginho.accounting.model.IncomeStatement" />
    </Report>
    <Report id="Revenue" template="RevenueTemplate.jasper">
      <Model id="revenue" class="de.togginho.accounting.model.Revenue" />
    </Report>
    <Report id="Expenses" template="ExpensesTemplate.jasper">
      <Model id="expenseCollection" class="de.togginho.accounting.model.ExpenseCollection" />
    </Report>
  </Reports>
</AccountingReports>
